### ISSUE TITLE
obfs

### ISSUE THREAD

**Issue by infinitaa** [lotusnetwork/bodhi-docker#3]
I'm afraid there is no any documentation about obfs usage. I checked the source and it get only true and false and puts it in obfs password section.

**Comment by infinitaa** [comment]
This is the node config
I set obfs to "true"
I doesnt connect
![Screenshot 2023-10-09 192903](https://github.com/lotusnetwork/bodhi-docker/assets/121110779/0305e9af-e613-4b4d-84e3-bb3dbd5bdf13)

**Comment by lotusnetwork** [comment]
When you set to true, obfs password is pulled from your lotusboard, and you'll need to modify the php source code so that obfs will appear in your subscription link

**Comment by lotusnetwork** [comment]
uncomment the obfs line
